### ISSUE TITLE
Fagopplæring

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#213]
LIGGER PÅ VENT TIL VI TAR FATT PÅ FAGOPPLÆRINGEN - OPPRETTER NY(E) ISSUES KNYTTET TIL DET ARBEIDET

Faglig opplæring
- [ ] Avklaringer mot ABS knyttet til on-boarding - møte rund påsketider
- [ ] Børre kaller oppstartsmøte for planlegging av rigging faglig opplæring ifbm on-boarding i avdelingen
- [ ] Oppstartsmøte gjennomført
- [ ] Planlegge WS
- [ ] Gjennomføre WS

## Status
13.12: Ws med fokus på aktiviteter på kort sikt. 
- Gjennomgang og redigering av mal for sidenFagopplæring i Teams: 
- Fagpersoner kalles inn til møte i uke 2 . Lise kaller inn
  Agenda: informere om oppgaven "samle og utarbeide dokumentasjon for faglig opplæring" for nye ansatte
5.12.2022: Lise har kalt inn til planleggingsmøte i uke 49
28.11.2022: Lise kaller inn til møte, hvordan organiserer vi arbeidet, hvordan onbaordes i team, og hvordan læres opp innen en rolle.
7.11.2022: Gjennomført først møte, opprettet eget arbeidsområde på teams. Børre lager skisse basert på bildene. Lise kaller til videre arbeidsmøter.
31.10.2022: Lise kaller inn til møte for å definere denne aktiviteten. Børre deltar i dette møtet.
3.8.2022:
- hadde møte med Hanne og hun skal se på dette - kanskje det tar litt lengre tid en antatt. Vi snakket også om opplæringsplanen - ønsker at denne blir delt; en generell del som alle skal gjennom og den andre delen som spisses til å gjelde den nyansattes rolle (dette jobber Hanne med å se på).

23.6.2022:
- Fagområdene som skal bygges taes fortløpende etter behov. IT-utvikler, designer og jurist er de første vi tar for oss. Resten vil bli tatt nå behovet dukker opp.
- Fagopplæringen dokumenteres i Teams under BOD - Opplæring
- Materiale flyttet fra confluence, blir gjennomgått og omarbeidet i teams.
- Neste steg:
-  overlate ansvaret til teamene og leder som skal bidra inn i arbeidet med dokumenteringen.
- Bygge malverk for fagopplæring (PPT eller i det format som er ønskelig, teamsstrukturen)

- Vi er tilgjengelig for veiledning knyttet til utforming/bygging av dokumentasjonen.

Hva må vi ta stilling:
- [x] Ta stilling til hvilke fagområdet vi skal bygge opp dokumentasjon på
- [x] Hvor skal fagopplæringen dokumenteres og på hvilke format
- [x] Samle det materialet vi har og foreta en gjennomgang av dette
- [x] Vurdere 1 til 1 møte med de som skal lage dette for å være tydelig på hva vi ønsker.

Oppgaver:
- [ ] Hvor skal vi lagre filer ol. Eks Design har presentasjoner på sitt område i Teams som kanskje burde ligge under BOD Opplæring.
- [ ] Overlever oppgave med tilrettelegging av fagdokumentasjon til leder
- [ ] Bygge malverk knyttet til fagopplæring
- [x] Flytte dokumentasjonen som finnes rundt fagopplæring inn i teams
- [ ] Oppfølging av teamene: status og framdrift, lagring av dokumentasjon
- [ ] Arrangere møte for fagpersoner innen design, it, jus, ABS, økonomi som skal ta imot nye ansatte første halvdel av 23
- [ ] Redigere Fagopplæring på Teams-området

**Comment by borrehovstol** [comment]
Denne lukkes da det jobbes videre med dette i issue #423
