### ISSUE TITLE
Utarbeide årshjul knyttet til kompetanse

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#214]
Årshjulet bygger vi parallelt med annen aktivitet. 
Legg inn i listen under når det dukker opp ting vi mener at må være med i årshjulet.

- [ ] Revisjon/oppdatering av årshjulet (må avklare hvor ofte).
- [ ] Revisjon av roller knyttet til onboarding (mentor, fadder, rollebeskrivelse)
- [ ] Revisjon av beskrivelser knyttet til avgrensninger/omfang på Teams-områdene (se #235)
- [ ] Revisjon av Teams-områdene våre, lage sjekkliste om hva som skal gjøres i en revisjon.
- [ ] Henvendelse mot lederlaget angående praksiselever - ressurser knyttet til dette osv.
- [ ] Sommer-camp, avklares Team kompetanse sin rolle (fra år til år)
- [ ] Praksis-studenter fra høyskole/universitet - avklaringer knyttet til dette.

**Comment by borrehovstol** [comment]
Denne er lukket da årshjulet er etablert og vi fyller inn aktiviteter direkte i årshjulet.
