### ISSUE TITLE
Lage oversikt over maler vi ikke har

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/metode-kompetanse#258]
Status:

- 

______________________________________________________________________________________
Her bygger vi listen over maler vi ser vi ikke har/som må gjennomgås og revideres:

- [ ] Mal opplæringstiltak - gjennomgang
- [x] Tidsplan onboarding- gjennomgang
- [x] Melde inn behov for kompetanseheving- gjennomgang
- [ ] Beskrive opplæringstiltak/kurs- gjennomgang
- [ ] Invitasjon kurs- gjennomgang
- [ ] Individuell opplæringsplan (gjennomgang)

[Oversikt over maler vi har ](https://digdir.sharepoint.com/:x:/r/sites/Metodeogkompetanse/Delte%20dokumenter/Kompetanse/Arbeidsomr%C3%A5de%20Lise%20og%20B%C3%B8rre/Forslag%20til%20ny%20struktur%20under%20Team%20kompetanse%20(denne%20legger%20vi%20rett%20under%20General%20n%C3%A5r%20den%20er%20ferdig)/Kartlegging%20av%20dokumenter%20Teams%20og%20Conflucence/Oversikt%20maler%20rutiner.xlsx?d=w8121456d0b254e66b4dc4314dafea255&csf=1&web=1&e=yoPNf1)

**Comment by L-MIA** [comment]
Se oversikt over [maler](https://digdir.sharepoint.com/:x:/r/sites/Metodeogkompetanse/Delte%20dokumenter/General/Team%20kompetanse%20og%20oppl%C3%A6ring/Arbeidsomr%C3%A5de%20Lise%20og%20B%C3%B8rre/Kartlegging%20av%20dokumenter%20Teams%20og%20Conflucence/Oversikt%20maler%20rutiner.xlsx?d=w8121456d0b254e66b4dc4314dafea255&csf=1&web=1&e=KdRq3W)

**Comment by borrehovstol** [comment]
Dette er lagt til #222 og vil ikke bli jobbet videre med her.
