### ISSUE TITLE
Revidere ppp: Velkommen til BOD 

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#260]
## Status:
4.4.22: avventer på ferdigstillelse av [Startsiden under BOD generelt](https://teams.microsoft.com/l/channel/19%3A724f06d6fba342839bf842044fb5a3dd%40thread.skype/tab%3A%3Acb97ab98-c12a-4791-a8ad-4e3fae0cd428?groupId=3909c1de-10a4-4fb8-a295-42adb91be175&tenantId=008e560f-08af-4cec-a056-b35447503991). 

Revidere og forbedre avdelingdirektørs presentasjon av Digdir/BOD.
Eli Helen Korsan har hovedansvaret.

**Comment by L-MIA** [comment]
21.02: Gjennomgang av eksisterende ppp på 52 lysbilder.

**Comment by borrehovstol** [comment]
Denne lukkes da vi har dublet. Se issue #270
