### ISSUE TITLE
Hvordan lagre vurderinger av praksiselever

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#281]
## Status:
28.11.2022: Skolens evalueringsskjema benyttes og vi har derfor ingen data som lagres hos oss i etterkant. Dette medfører at vi ikke har data som lagres og trenger ikke tenke på personvernet rundt disse ressursene.
24.5.2022:
- taes fortløpende når vi får inn praksisstudent til høsten

## Brukerhistorie
- [ ] Som opplæringsansvarlig ønsker jeg å få avklart hvor og hvor lenge vurderinger av praksiselever bør lagres slik at elevenes personvern ivaretas.

**Comment by borrehovstol** [comment]
Lukkes på bakgrunn av siste status.
