### ISSUE TITLE
Onboarding: Kvalitetssikring presentasjoner 

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#322]
## Status

##Beskrivelse
Presentasjonene som brukes i onboarding må kvalitetssikres mhp innhold: gjentakelser, målgruppe/nivå

## Oppgaver
- [ ] Samle presentasjoner på Teams>opplæring
- [ ] gjennomgang og vurdering av innhold
- [ ] gjennomgang med de som har utarbeidet presentasjonene
- [ ] Evt forbedring/videreutvikling av innhold

## Akseptanse kriterium
- [ ]  Oppgave er utført, på riktig måte og med riktig resultat

**Comment by borrehovstol** [comment]
Vil ikke bli jobbet med
