### ISSUE TITLE
Onboarding: Presentasjon av Altinn - ny versjon

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#323]
##Status
8.3.2023: Arbeidsmøte for å få ferdigstilt presentasjon til 14.3.2023.
20.02 Gjennomgang av eksisterende presentasjoner.  Hilde og Børre lager et utkast.
15.02 Møte med Cathrine, Hilde og Lise: 
- struktur for opplegget
   -presentasjon 
   - medlytt ABS
   
- planlegging 
- deling av lenker til gamle pp
uke 6: oppstart: Forberedelser til oppgaven
20.09 Møte med Trude (Komm) ang ny presentasjon av Altinn. 

## Krav til kartlegging
- [x] Hva har vi allerede i avdeling BOD på denne oppgaven
- [x] Hva kan brukes ?

## Oppgaver:
- [x] Lage struktur/skall for presentasjonen
- [x] Se på hvilke foiler som kan brukes
- [ ] Arbeidsmøte for å lage nye foiler
- [ ] Sjekke ut innhold med fagansvarlige
- [ ] Ferdigstille første utgave som kan benyttes i opplæring den 15.3.2023.
- [ ] Jobbe videre med presentasjonen slik at den blir komplett til fremtidig bruk i avdelingen.
- [ ] Koble på Komm

[Lenke til arbeidsområdet i teams ](https://digdir.sharepoint.com/:f:/r/sites/Metodeogkompetanse/Delte%20dokumenter/Kompetanse/Arbeidsomr%C3%A5de/%23323%20Onboarding%20Presentasjon%20av%20Altinn%20-%20ny%20versjon?csf=1&web=1&e=NppgQr)

**Comment by borrehovstol** [comment]
Lukker denne da vi per nå ikke kommer til å jobbe med denne, samt at Baksiden vil dekke en del av denne informasjonen.
