### ISSUE TITLE
Evaluering av kurs og onboaring

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#324]
## Status
- 

## Oppgaver
- [ ] Lage en standard evaluering av opplæringstiltak som kan tilpasses ulike behov

## Krav til kartlegging
- [ ] Hva har vi allerede i avdeling BOD på denne oppgaven
- [ ] Hva har vi allerede i Digdir på denne oppgaven

## Brukerhistorien består av følgende oppgaver:
- [ ] Finne verktøy/metode
- [ ]Lage standard som kan tilpasses behov
- [ ] ..
- [ ] Oppgav n

**Comment by borrehovstol** [comment]
Lukker denne da vi ikke kommer til å jobbe med denne issuen videre.
