### ISSUE TITLE
Onboarding som del av BODs startside

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#327]
## Status
30.09 Forespørsel fra Randi: bør Onboarding inn som egen arkfane i prototypen/Startsiden?
06.10 Reidun tok en kjapp demo på prototypen
07.10 Lise etterlyste lenke til siden

## Brukerhistorie
- [ ] Som <rolle/person> ønsker jeg <oppgave/mål> slik at <resultat/forbedring>

## Krav til kartlegging
- [ ] Hva har vi allerede i avdeling BOD på denne oppgaven
- [ ] Hva har vi allerede i Digdir på denne oppgaven
- [ ] Hva har vi allerede i andre etater på denne oppgaven

## Brukerhistorien består av følgende oppgaver:
- [ ] Oppgave 1
- [ ] Oppgave 2
- [ ] ..
- [ ] Oppgav n

## Akseptanse kriterium
- [ ]  Oppgave er utført, på riktig måte og med riktig resultat

## Brukerhistorie eksempel
![image](https://user-images.githubusercontent.com/72547415/155699147-36e7d830-a8a7-4613-946e-de53f7715b61.png)

**Comment by borrehovstol** [comment]
Denne er løst, on-boarding er etablert på [baksiden](https://blue-sand-086e7ab03.2.azurestaticapps.net/brukeropplevelse-og-datadeling/onboarding/)
