### ISSUE TITLE
Onboarding av praktikant

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#333]
## Krav til kartlegging
- [ ] Hva kan gjenbrukes av andre opplegg?
- [ ] Hvilke aktiviteter som er planlagte for andre kan praktikanten delta på?
- [ ] 

## Brukerhistorien består av følgende oppgaver:
- [ ] Oppgave 1
- [ ] Oppgave 2
- [ ] ..
- [ ] Oppgav n

**Comment by borrehovstol** [comment]
Blir ikke jobbet med, er lagt inn i samle-issue #383
