### ISSUE TITLE
Presentasjon av opplæring og rekruttering på Infomøtet i BOD

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#334]
## Status
27.10.22 Tentativ dato uke 48

## Krav til kartlegging
- [ ] Presentasjon brukt i lederlaget 06.09.22
- [ ] 

## Brukerhistorien består av følgende oppgaver:
- [ ] Oppgave 1
- [ ] Oppgave 2
- [ ] ..
- [ ] Oppgav n

**Comment by borrehovstol** [comment]
Blir ikke jobbet med, er lagt inn i samle-issue #383
