### ISSUE TITLE
Presentasjoner av Digdir, BOD og seksjoner

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#335]
## Krav til kartlegging
- [ ] Hva er gjort avdeling BOD?
- [ ] Hva har vi allerede i Digdir på denne oppgaven?
- [ ]

## Brukerhistorien består av følgende oppgaver:
- [ ] Oppgave 1
- [ ] Oppgave 2
- [ ] ..
- [ ] Oppgav n

**Comment by borrehovstol** [comment]
Blir ikke jobbet med, er lagt inn i samle-issue #383
