### ISSUE TITLE
Work shop: Bedre opplegg for onboarding

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#336]
## Status 

- Innspill med forslag om ulike endringer fra nye ansatte (Gørild, Terje Sylvarnes og Kjersti Steien)

## Krav til kartlegging
- [ ] Hva har vi allerede i avdeling BOD på denne oppgaven
- [ ] Hva har vi allerede i Digdir på denne oppgaven
- [ ] Hva har vi allerede i andre etater på denne oppgaven

## Brukerhistorien består av følgende oppgaver:
- [ ] Oppgave 1
- [ ] Oppgave 2
- [ ] ..
- [ ] Oppgav n

**Comment by borrehovstol** [comment]
Blir ikke jobbet med, er lagt inn i samle-issue #383

**Comment by borrehovstol** [comment]
Lukker denne da dette blir håndtert i andre aktiviteter.
