### ISSUE TITLE
Forbedre plan for onboarding

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#343]
## Status

06.02 Lise kaller inn Anne Marthe til et møte for oppklaring av oppgavefordeling HR/avdelinger
- organisering
- prioritering

- 02.02 PP-presentasjon av organisering klar til gjennomgang (Hilde)
- Møte med HR/Ashab

- Oppgavefordeling
-16.01.23: Workshop: nytt opplegg for onboarding (Børre og Lise)
- 19.12.2022: Gjennomgang av dagens opplegg og forslag til nytt opplegg. Deler av dagens opplegg blir del av fag-/team opplæring. Baksia danner base for nytt opplegg, og ansv for gjennomføring blir i opplæringslaget.
Lise kaller inn til nytt møte. 
- 13.12Lise har kalt inn til nytt møte mandag 19.12.2022.
- 13.12 Oversikt over oppgaver med forslag til endring lagt ut på [Teams](https://digdir.sharepoint.com/:w:/r/sites/Metodeogkompetanse/Delte%20dokumenter/Kompetanse/Arbeidsomr%C3%A5de/%23343%20%20Struktur%20onboarding/Onboarding%20tidsplan.docx?d=w5bff370d076b40ebab4ef24c09ee1db9&csf=1&web=1&e=rwkUGL).
- 12.1222 WS for å planlegge oppstart av oppgaven. 

## Krav til kartlegging
- [ ] Hva har vi allerede i avdeling BOD på denne oppgaven
- [ ] Hvordan fordele aktivitetene slik at det passer best mulig til de ulike onboardingsområdene?
-

## Brukerhistorien består av følgende oppgaver:
- [ ] Gjennomgang av det som allerede eksisterer
- [ ] Vurdere
- [ ] ..
- [ ] Oppgav n

**Comment by borrehovstol** [comment]
Dette blir håndtert i issue #388
