### ISSUE TITLE
Introduksjonskurs i Github for ABS 23. mars

### ISSUE THREAD

**Issue by hildemari** [Altinn/metode-kompetanse#360]
Vi må finne ut hva vi gjør med Github-kursene, det er stor etterspørsel men for liten kapasitet i opplæringesteamet. 
 Status 6.2.2023 Lise, Arild og Hilde hadde møte for å diskutere hvilke alternativer vi har.  

- [x] Planlegge GitHub opplæring for ABS med Hege
- [x] Fastsette kursdatoer
- [x] Sende ut innkalling til kurs.
- [x] Sende ut informasjon om opprettelse av bruker i Github til kurs
- [x] Sjekke om alle har fått opprettet bruker
- [x] Evt forbedre kursmateriell
- [x] Møte med Elaine for å ta en gjennomgang av kursmateriell og gjennomføring
- [x] Gjennomføre GitHub kurs for ABS - benytte samme materiell som fysisk kurs i Brønnøysund (PPT og øvinger). 
- [x] Sende ut evaluering etter kurset til deltakerne
- [x] Gjennomgang av evalueringen

**Comment by borrehovstol** [comment]
Kurset gjennomført, gode tilbakemeldinger. Vi tar med oss innspillene videre for forbedring av kursinnholdet/gjennomføring.
