### ISSUE TITLE
Tilgang til vitenskapelige databaser

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#369]
## Status
13.02 Forespørsel videresendt Innkjøp. Svar: Ingen kjennskap til at det finnes avtaler.
02.02 Lise videresendte forespørsel til HR. Svar: Ingen kjennskap til dette
- 02.02. Henvendelse fra Odd Arne Sætervik ang behov for tilgang til vitenskapelige databaser

**Comment by borrehovstol** [comment]
Lukker denne da dette ikke er innenfor vårt område og HR kan ikke se at de har noe ansvar knyttet til dette.
