### ISSUE TITLE
Onboarding leders presentasjon av HR relaterte tema dag 1

### ISSUE THREAD

**Issue by L-MIA** [Altinn/metode-kompetanse#371]
## Status
uke 6: Cathrine gjennomgår tidligere presentasjoner fra HR for å lage en PP som ledere kan bruke dag 1 i onboarding

##Oppgaver
Se på tidligere presentasjoner
Sette sammen ny presentasjon oppdatert i fht behov og oppgavefordeling (BOD/HR)
Sjekke ut innhold med HR

**Comment by L-MIA** [comment]
Oppgaver:
Sjekke med HR/ledere om innholdet dekker behov

**Comment by borrehovstol** [comment]
Lukker denne da dette ligger utenfor det som er vårt ansvarsområde.
