### ISSUE TITLE
Onbarding Q1 2023

### ISSUE THREAD

**Issue by borrehovstol** [Altinn/metode-kompetanse#379]
MARS:
Forberedelse mottak av nyansatt
- [ ] Dialog med leder for avklaringer
- (x) Forberedelser til faglig opplæring med fagansvarlige og leder
- [ ] Opplæringsplan
- Satt opp men ikke iverksatt. Nyansatt informert om utsettelse til april
- [ ] Booke aktuelle møtetidspunkter for gjennomgang av de ulike opplæringstiltakene
- [ ] Booke ressurser for den praktiske gjennomføringen av de ulike opplæringstiltakene
- [ ] Underveis-samtale med nyansatte

Nyansatte som skal on-boardes i perioden:
- [ ]  Linda Solstad

## Akseptanse kriterium
Oppgave er utført når alle nyansatte har fått tilbud/vært gjennom planlagt opplæringsløp

**Comment by borrehovstol** [comment]
Nyansatte Q1 er on-boardet

**Comment by L-MIA** [comment]
Ikke helt korrekt da de er lovet å få tilbud om å delta på intro til altinn-opplegget.

Lise

Fra: Børre Hovstøl ***@***.***>
Sendt: tirsdag 28. mars 2023 13:36
Til: Altinn/metode-kompetanse ***@***.***>
Kopi: Lise Marie Ingebrigtsen Alsaker ***@***.***>; Assign ***@***.***>
Emne: Re: [Altinn/metode-kompetanse] Gjennomføring Onbarding Q1 (Issue #379)

[ Ekstern e-post ]

Nyansatte Q1 er on-boardet

-
