### ISSUE TITLE
Kartlegge rutiner i HR og BOD ved ansettelser

### ISSUE THREAD

**Issue by SnorreTE** [Altinn/metode-kompetanse#388]
Uklart hvilke rutiner som finnes og hvem som gjør hva når det ansettes nye. Bidra til å kartlegge hva som skjer hvor.

Melding om ansatte - egen epost kanal ved ansettelser/endring. Går til HR og IT blant annet.
- Sol sender inn ved anskaffelse eksterne konsulenter
- Jon Viggo har tilgang og oppretter SAP bruker (timer DFØ)

HR - rutiner ved ny ansatt?
- Arbeidsplass 
- PC/Utstyr
- Adgangskort 
- SAP bruker

- [x] Prat med Sol/Innkjøp om rutiner avrop konsulenter
- [x] Prat Børre for hva som allerede er kartlagt
- [x] Møte Sol, Børre, Arild, Ashab og Jon Viggo for informasjon den 26. april.
- [x] Avsjekk HR
- [x] Børre kaller inn Cathrine til videre arbeid knyttet til onboarding.

**Comment by borrehovstol** [comment]
Denne lukkes på bakgrunn av status i issuen.
