### ISSUE TITLE
Introduksjonkurs til Github og smidig metodikk - 29. juni 2023

### ISSUE THREAD

**Issue by ElaineSvartis** [Altinn/metode-kompetanse#417]
- [x] Ta kontakt med de som står på [liste ]
- [x] Avklare dato for kurset
- [x] Forberedelsesmøte før kurset
- [x] Booke møterom
- [x] Sende ut innkalling til kurs
- [x]  Oppdater kursmateriale
- [x]  Sende ut informasjon om opprettelse av brukere i Github
- [x]  Gjennomføre kurset
- [x]  Sende ut evaluering etter kurset til deltakerne
- [x]  Sende ut kursmateriell til deltakerne
- [x]  Gjennomgang av evalueringen
- [x]  Slette innsendte svar fra evalueringen

**Comment by borrehovstol** [comment]
@ElaineSvartis godt jobbet Elaine 👍 og @hildemari jeg har fått lagt issue i vårt board 🙂
