### ISSUE TITLE
Som ansatt må man utarbeidet målene for teamet for å utføre aktiviteter og arbeide i henhold til strategien.

### ISSUE THREAD

**Issue by WencheFylken** [Altinn/metode-kompetanse#71]
SE LISTE #75

**Comment by rmi-lab** [comment]
Kan vi legge denne sammen med #75

**Comment by WencheFylken** [comment]
Hvilke mål skal teamet oppnå ift strategi 4?

**Comment by WencheFylken** [comment]
Ja det kan vi .


Vennlig hilsen/Kindest regards


Wenche Fylken
Prosjektleder / projectmanager

Mob: +47 47259311
Grev Wedels Plass 9, 0151 Oslo, NO

***@***.***D73836.52DAF630]

Postboks 1382 Vika, 0114 Oslo, NO
digdir.no<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.digdir.no%2F&data=04%7C01%7C%7C16102a242e6142d3b8e908d88720840e%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637407921120975933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CQVImckg34YEYnXIHdr9bdBBy6A5bSjhTAoIX2FDqPk%3D&reserved=0>



Fra: Reidun Milde ***@***.***>
Sendt: fredag 23. april 2021 11:39
Til: Altinn/metode-kompetanse ***@***.***>
Kopi: Fylken, Wenche ***@***.***>; Author ***@***.***>
Emne: Re: [Altinn/metode-kompetanse] Som ansatt må man utarbeidet målene for teamet for å utføre aktiviteter og arbeide i henhold til strategien. (#71)


Kan vi legge denne sammen med #75<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAltinn%2Fmetode-kompetanse%2Fissues%2F75&data=04%7C01%7C%7C1a695c44735c419a20e208d9063bad64%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637547675644784929%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QoxxG202DgBBjuwEJdEkXTmdzKafBYeuPRNpBjY6soM%3D&reserved=0>

-

**Comment by WencheFylken** [comment]
inngår i oppgave 75
